name: Build Unity Project

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Unity Web Profile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Set up Unity
        uses: game-ci/unity-builder@v4.2.3
        with:
          unityVersion: 6000.0.32f1
          targetPlatform: WebGL
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Build with Custom Function
        run: |
          export UNITY_LOG_FILE=$(pwd)/unity_build.log
          unity-editor -batchmode -nographics -quit \
            -projectPath $(pwd) \
            -executeMethod BuildMazeGenerationWebProfile \
            -logFile $UNITY_LOG_FILE
          cat $UNITY_LOG_FILE

      - name: Move Build to Separate Directory
        run: |
          mkdir -p build_output
          mv Build/* build_output/ || echo "No build files found"

      - name: Commit and Push Build to 'builds' Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B builds
          git add build_output
          git commit -m "New Unity WebGL build"
          git push origin builds --force