name: Build Unity Project

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Unity Web Profile
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Étape 2: Cacher les dépendances Unity
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      # Étape 3: Installation de Unity
      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.0.32f1
          targetPlatform: WebGL
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

      # Étape 4: Vérifier l'installation d'Unity
      - name: Verify Unity Installation
        run: |
          /opt/Unity/Editor/Unity -version

      # Étape 5: Lancer le build Unity
      - name: Build Unity Project
        run: |
          echo "Starting the build..."
          export UNITY_LOG_FILE=$(pwd)/unity_build.log
          /opt/Unity/Editor/Unity -batchmode -nographics -quit \
            -projectPath $(pwd) \
            -executeMethod BuildMazeGenerationWebProfile \
            -logFile $UNITY_LOG_FILE
          cat $UNITY_LOG_FILE

      # Étape 6: Déplacer le build dans un dossier spécifique
      - name: Move Build to Separate Directory
        run: |
          mkdir -p build_output
          mv Build/* build_output/ || echo "No build files found"

      # Étape 7: Commit et Push sur la branche 'builds'
      - name: Commit and Push Build to 'builds' Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B builds
          git add build_output
          git commit -m "New Unity WebGL build"
          git push origin builds --force
