name: Build Unity Project

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Unity Web Profile on Windows
    runs-on: windows-latest

    steps:
      # Étape 1: Checkout du code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Étape 2: Cacher les dépendances Unity
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      # Étape 3: Installer Unity avec le lien fourni
      - name: Install Unity
        run: |
          Invoke-WebRequest -Uri https://download.unity3d.com/download_unity/b2e806cf271c/Windows64EditorInstaller/UnitySetup64-6000.0.32f1.exe -OutFile UnitySetup64-6000.0.32f1.exe
          Start-Process -Wait -FilePath UnitySetup64-6000.0.32f1.exe -ArgumentList "/S /D=C:\Unity"
          Remove-Item -Force UnitySetup64-6000.0.32f1.exe

      # Étape 4: Vérification de l'installation d'Unity
      - name: Verify Unity Installation
        run: |
          & "C:\Unity\Editor\Unity.exe" -version

      # Étape 5: Créer un répertoire pour les logs et lancer le build Unity
      - name: Prepare for Build
        run: |
          # Créer un répertoire spécifique pour les logs Unity
          New-Item -Path "C:\build_logs" -ItemType Directory -Force

          echo "Starting the build..."
          $env:UNITY_LOG_FILE = "C:\build_logs\unity_build.log"
          & "C:\Unity\Editor\Unity.exe" -batchmode -nographics -quit `
            -projectPath "$(pwd)" `
            -executeMethod BuildMazeGenerationWebProfile `
            -logFile $env:UNITY_LOG_FILE

      # Étape 6: Lire le contenu du fichier de log pour obtenir des détails
      - name: Show Build Log
        run: |
          Get-Content "C:\build_logs\unity_build.log"

      # Étape 7: Déplacer le build dans un dossier spécifique
      - name: Move Build to Separate Directory
        run: |
          New-Item -Path build_output -ItemType Directory -Force
          Move-Item -Path Build\* -Destination build_output\ -Force

      # Étape 8: Commit et Push sur la branche 'builds'
      - name: Commit and Push Build to 'builds' Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B builds
          git add build_output
          git commit -m "New Unity WebGL build"
          git push origin builds --force
