name: Build Unity Project 🛠️

on: push

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 6000.0.32f1
          targetPlatform: StandaloneLinux64
          buildMethod: BuildScript.BuildMazeGeneratorWithWebProfile

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build

  deploy:
    name: Deploy to builds branch
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          ref: builds

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: build

      - name: Commit and push build
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          mkdir -p Linux
          mv build/* Linux/
          git add Linux/
          git commit -m 'Add new build'
          git push origin builds
