name: MazeGenerator CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Setup Unity
    #   run: |
    #     echo "${{ secrets.UNITY_LICENSE }}" > Unity_v6000.0.32f1.ulf
    #     "C:\Program Files\Unity\Hub\Editor\6000.0.32f1\Editor\Unity.exe" -batchmode -manualLicenseFile Unity_v6000.0.32f1.ulf -logfile

    - name: Build project
      run: |
        "C:\Program Files\Unity\Hub\Editor\6000.0.32f1\Editor\Unity.exe" -quit -batchmode -nographics -logFile -projectPath . -executeMethod BuildScript.BuildMazeGeneratorWithWebProfile
