name: Setup Unity

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Setup Unity Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Activate Unity License
        run: |
          echo "$UNITY_LICENSE" | base64 --decode > Unity.ulf
          mv Unity.ulf /tmp/Unity.ulf  # Déplace la licence hors du dépôt
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Install Unity Editor
        run: |
          UNITY_VERSION=6000.0.32f1
          wget https://download.unity3d.com/download_unity/b2e806cf271c/LinuxEditorInstaller/Unity-6000.0.32f1.tar.xz
          tar -xf Unity-6000.0.32f1.tar.xz -C /opt/
          sudo ln -s /opt/Unity-6000.0.32f1/Editor/Unity /usr/local/bin/Unity
          sudo ln -s /opt/Unity-6000.0.32f1/Editor/Unity /usr/local/bin/UnityHub

  
