name: GameCI Template

on: push

jobs:
  checkLicense:
    name: Check for the Unity license
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} 
    steps:
      - name: Fail - No license
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1
  testRunner:
    needs: checkLicense
    name: Test All Modes
    runs-on: ubuntu-latest 
    steps:
    -   name: Checkout code
        uses: actions/checkout@v2

    -   name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

    -   name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
            path: .git/lfs
            key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id')}}

    -   name: Git LFS Pull
        run: |
            git lfs pull
            git add .
            git reset --hard

    -   name: restore Library cache
        uses: actions/cache@v2
        with:
            path: Library
            key: Library-test-project
            restore-keys: |
                Library-test-project-
                Library-

    -   uses: webbertakken/unity-test-runner@v2
        id: testRunner
        with:
            testMode: all
    
    -   uses: actions/upload-artifact@v2
        with:
            name: Test results (all modes)
            path: ${{steps.testRunner.outputs.artifactsPath}}
