name: GameCI Template

on: push

jobs:
  checkLicense:
    name: Check for the Unity license
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}  # Utilisation correcte du secret
    steps:
      - name: Fail - No license
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1
